language: node_js
node_js:
  - '10'
dist: trusty
sudo: true

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - ng lint
  - npm run test:badges
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search

notifications:
  email:
    on_failure: change
    on_success: change
